/*
 * msg_proc.c:
 * 
 * Adapted from: https://docs.oracle.com/cd/E19683-01/816-1435/rpcgenpguide-21470/index.html
 * 
 * This file contains the server-side functoin for printing a
 * message. It must be written manually by developers.  
 * 
 * For rpcgen, server-side functions must be named in a very specific
 * way.  The function must be have the same as the correspending
 * definition in the interface definiton file (.x) except in all
 * lowercase.  Futhermore, it must be appended with the version number
 * ("1") and the letters "svc" for service.
 */
#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "msg.h"    /* msg.h generated by rpcgen */
 
int *
printmessage_1_svc(struct messagelist *msg, struct svc_req *req)
{
  static int result;  /* must be static! */
  FILE *f;
  
  f = fopen("output", "w");
  //	f = fopen("/dev/console", "w");
  if (f == (FILE *)NULL) {
    result = 0;
    return (&result);
  }
  fprintf(f, "%s %d\n", msg->name, msg->count);
  fprintf(f, "%s %d\n", msg->next->name, msg->next->count);
  fclose(f);
  result = 1;
  return (&result);
}
