/*
 * Adapted from:
 *  https://docs.oracle.com/cd/E19683-01/816-1435/rpcgenpguide-21470/index.html
 * 
 * This is the client-side code that issues the remote procedure call.
 * It is also manually written by developers.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "msg.h"			/* msg.h generated by rpcgen */
 
int main(int argc, char *argv[])
{
  CLIENT *clnt;
  int *result;
  struct messagelist *message; 
  char *server;
  
  if (argc != 4) {
    fprintf(stderr, "usage: %s host message\n", argv[0]);
    exit(1);
  }

  server = argv[1];
  message = malloc(sizeof(messagelist));
  message->count = 1;
  message->name = argv[2];
  message->next = malloc(sizeof(messagelist));
  message->next->name = argv[3];
  message->next->count = 2;
  message->next->next = NULL;

  /*
   * Create client "handle" used for 
   * calling MESSAGEPROG on the server
   * designated on the command line.
   */
  
  /* Client create takes as input the machine to contact (server), the
   * "program" ("MESSAGEPROG") within which the function resides on the
   * server, the version number of the remote function to execute, and
   * the protocol to use for network communication ("tcp").
   * 
   * You can think of program as just a set of things that logially
   * encapsulate a set of related functions offered by the server.
   */
  clnt = clnt_create(server, MESSAGEPROG,
		     PRINTMESSAGEVERS,
		     "tcp");
  if (clnt == (CLIENT *)NULL) {
    /*
     * Couldn't establish connection
     * with server.
     * Print error message and die.
     */
    clnt_pcreateerror(server);
    exit(1);
  }
  
  /*
   * Call the remote procedure
   * "printmessage" on the server
   */
  result = printmessage_1(message, clnt);

  if (result == (int *)NULL) {
    /*
     * An error occurred while calling 
     * the server.
     * Print error message and die.
     */
    clnt_perror(clnt, server);
    exit(1);
  }
  /* Okay, we successfully called 
   * the remote procedure. 
   */
  if (*result == 0) {
    /*
     * Server was unable to print 
     * our message.
     * Print error message and die.
     */
    fprintf(stderr,
	    "%s: could not print your message\n",argv[0]);
    exit(1);
  }
  /* The message got printed on the
   * server's console
   */
  printf("Message delivered to %s\n",
	 server);
  clnt_destroy(clnt);
  
  free(message->next);
  free(message);
  
  exit(0);
}
